version: "2.1"
services:
  ombi:
    container_name: ombi
    image: linuxserver/ombi:latest
    volumes:
      - ./config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Ljubljana
